import Navi from "@/components/Navi";
import "./globals.css";
import { Baloo_Bhai_2, Noto_Sans_KR } from "next/font/google";

const notoSansKr = Noto_Sans_KR({
  subsets: ["latin"],
  variable: "--NotoSans",
});
const balooBhai = Baloo_Bhai_2({
  subsets: ["latin"],
  variable: "--Baloo",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${notoSansKr.variable} ${balooBhai.variable}`}>
        <Navi />
        {children}
      </body>
    </html>
  );
}
