FROM python:3.11.4

WORKDIR /usr/src/backend

# COPY <local file or directory> <image directory>
COPY ../pip_requirements.txt ./

RUN pip install -r pip_requirements.txt

CMD [ "python", "manage.py", "runserver" ]`